type FieldNamedLocalizedService {
  Root(filter: [FieldNamedLocalizedService_Root_filter], orderBy: [FieldNamedLocalizedService_Root_orderBy], skip: Int, top: Int): FieldNamedLocalizedService_Root_connection
  localized(filter: [FieldNamedLocalizedService_localized_filter], orderBy: [FieldNamedLocalizedService_localized_orderBy], skip: Int, top: Int): FieldNamedLocalizedService_localized_connection
}

type FieldNamedLocalizedService_Root {
  ID: Int
  localized(filter: [FieldNamedLocalizedService_localized_filter], orderBy: [FieldNamedLocalizedService_localized_orderBy], skip: Int, top: Int): FieldNamedLocalizedService_localized_connection
}

input FieldNamedLocalizedService_Root_C {
  ID: Int
  localized: [FieldNamedLocalizedService_localized_C]
}

input FieldNamedLocalizedService_Root_U {
  localized: [FieldNamedLocalizedService_localized_C]
}

type FieldNamedLocalizedService_Root_connection {
  nodes: [FieldNamedLocalizedService_Root]
  totalCount: Int
}

input FieldNamedLocalizedService_Root_filter {
  ID: [Int_filter]
}

type FieldNamedLocalizedService_Root_input {
  create(input: [FieldNamedLocalizedService_Root_C]!): [FieldNamedLocalizedService_Root]
  delete(filter: [FieldNamedLocalizedService_Root_filter]!): Int
  update(filter: [FieldNamedLocalizedService_Root_filter]!, input: FieldNamedLocalizedService_Root_U!): [FieldNamedLocalizedService_Root]
}

input FieldNamedLocalizedService_Root_orderBy {
  ID: SortDirection
}

type FieldNamedLocalizedService_input {
  Root: FieldNamedLocalizedService_Root_input
  localized: FieldNamedLocalizedService_localized_input
}

type FieldNamedLocalizedService_localized {
  ID: Int
  localized: String
  root: FieldNamedLocalizedService_Root
}

input FieldNamedLocalizedService_localized_C {
  ID: Int
  localized: String
  root: FieldNamedLocalizedService_Root_C
}

input FieldNamedLocalizedService_localized_U {
  localized: String
  root: FieldNamedLocalizedService_Root_C
}

type FieldNamedLocalizedService_localized_connection {
  nodes: [FieldNamedLocalizedService_localized]
  totalCount: Int
}

input FieldNamedLocalizedService_localized_filter {
  ID: [Int_filter]
  localized: [String_filter]
}

type FieldNamedLocalizedService_localized_input {
  create(input: [FieldNamedLocalizedService_localized_C]!): [FieldNamedLocalizedService_localized]
  delete(filter: [FieldNamedLocalizedService_localized_filter]!): Int
  update(filter: [FieldNamedLocalizedService_localized_filter]!, input: FieldNamedLocalizedService_localized_U!): [FieldNamedLocalizedService_localized]
}

input FieldNamedLocalizedService_localized_orderBy {
  ID: SortDirection
  localized: SortDirection
}

input Int_filter {
  eq: Int
  ge: Int
  gt: Int
  in: [Int]
  le: Int
  lt: Int
  ne: [Int]
}

type Mutation {
  FieldNamedLocalizedService: FieldNamedLocalizedService_input
}

type Query {
  FieldNamedLocalizedService: FieldNamedLocalizedService
}

enum SortDirection {
  asc
  desc
}

input String_filter {
  contains: [String]
  endswith: String
  eq: String
  ge: String
  gt: String
  in: [String]
  le: String
  lt: String
  ne: [String]
  startswith: String
}