type CompositionOfAspectService {
  Books(
    filter: [CompositionOfAspectService_Books_filter]
    orderBy: [CompositionOfAspectService_Books_orderBy]
    skip: Int
    top: Int
  ): CompositionOfAspectService_Books_connection
}

type CompositionOfAspectService_Books {
  chapters(
    filter: [CompositionOfAspectService_Books_chapters_filter]
    orderBy: [CompositionOfAspectService_Books_chapters_orderBy]
    skip: Int
    top: Int
  ): CompositionOfAspectService_Books_chapters_connection
  id: ID
  reviews(
    filter: [CompositionOfAspectService_Books_reviews_filter]
    orderBy: [CompositionOfAspectService_Books_reviews_orderBy]
    skip: Int
    top: Int
  ): CompositionOfAspectService_Books_reviews_connection
}

input CompositionOfAspectService_Books_C {
  chapters: [CompositionOfAspectService_Books_chapters_C]
  id: ID
  reviews: [CompositionOfAspectService_Books_reviews_C]
}

input CompositionOfAspectService_Books_U {
  chapters: [CompositionOfAspectService_Books_chapters_C]
  reviews: [CompositionOfAspectService_Books_reviews_C]
}

type CompositionOfAspectService_Books_chapters {
  id: ID
}

input CompositionOfAspectService_Books_chapters_C {
  id: ID
}

type CompositionOfAspectService_Books_chapters_connection {
  nodes: [CompositionOfAspectService_Books_chapters]
  totalCount: Int
}

input CompositionOfAspectService_Books_chapters_filter {
  id: [ID_filter]
}

type CompositionOfAspectService_Books_chapters_input {
  create(
    input: [CompositionOfAspectService_Books_chapters_C]!
  ): [CompositionOfAspectService_Books_chapters]
  delete(
    filter: [CompositionOfAspectService_Books_chapters_filter]
  ): Int
}

input CompositionOfAspectService_Books_chapters_orderBy {
  id: SortDirection
}

type CompositionOfAspectService_Books_connection {
  nodes: [CompositionOfAspectService_Books]
  totalCount: Int
}

input CompositionOfAspectService_Books_filter {
  id: [ID_filter]
}

type CompositionOfAspectService_Books_input {
  create(
    input: [CompositionOfAspectService_Books_C]!
  ): [CompositionOfAspectService_Books]
  delete(
    filter: [CompositionOfAspectService_Books_filter]
  ): Int
  update(
    filter: [CompositionOfAspectService_Books_filter]
    input: CompositionOfAspectService_Books_U!
  ): [CompositionOfAspectService_Books]
}

input CompositionOfAspectService_Books_orderBy {
  id: SortDirection
}

type CompositionOfAspectService_Books_reviews {
  id: ID
}

input CompositionOfAspectService_Books_reviews_C {
  id: ID
}

type CompositionOfAspectService_Books_reviews_connection {
  nodes: [CompositionOfAspectService_Books_reviews]
  totalCount: Int
}

input CompositionOfAspectService_Books_reviews_filter {
  id: [ID_filter]
}

type CompositionOfAspectService_Books_reviews_input {
  create(
    input: [CompositionOfAspectService_Books_reviews_C]!
  ): [CompositionOfAspectService_Books_reviews]
  delete(
    filter: [CompositionOfAspectService_Books_reviews_filter]
  ): Int
}

input CompositionOfAspectService_Books_reviews_orderBy {
  id: SortDirection
}

type CompositionOfAspectService_input {
  Books: CompositionOfAspectService_Books_input
  Books_chapters: CompositionOfAspectService_Books_chapters_input
  Books_reviews: CompositionOfAspectService_Books_reviews_input
}

input ID_filter {
  eq: [ID]
  ge: [ID]
  gt: [ID]
  le: [ID]
  lt: [ID]
  ne: [ID]
}

type Mutation {
  CompositionOfAspectService: CompositionOfAspectService_input
}

type Query {
  CompositionOfAspectService: CompositionOfAspectService
}

enum SortDirection {
  asc
  desc
}
